In [1]:
import numpy as np

In [4]:
porridge = np.array([79,65,50,63,56,90,85,98,79,51])
print(porridge)

[79 65 50 63 56 90 85 98 79 51]


In [6]:
cold = porridge[porridge < 60]
print(cold)

[50 56 51]


In [7]:
hot = porridge[porridge > 80]
print(hot)

[90 85 98]


In [11]:
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[79 65 63 79]
