## NumPy 배열

In [1]:
# Python 패키지 설치 명령어
!pip install numpy

In [2]:
# NumPy 불러오기
import numpy as np

In [3]:
# NumPy array(ndarray) 생성하기
my_list = [1,2,3,4,5,6]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5 6]


In [4]:
# 리스트/NumPy 배열 동시에 생성
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [7]:
# List comprehension vs. NumPy array

# Case: List comprehension
prices = [20, 40, 35, 10, 25, 56]
new_prices = [price-5 for price in prices]
print(new_prices)

# Case: NumPy array
prices_arr = np.array(prices)
prices_arr -= 5   # element-wise operation
print(prices_arr)

[15, 35, 30, 5, 20, 51]
[15 35 30  5 20 51]


In [11]:
"""
Exercise: 시험 점수 처리
"""

# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [12]:
# 세 번째 시험에 2점씩 더하기
test_3_fixed = test_3 + 2
print(test_3_fixed)

[89 87 74 92 94]


In [14]:
# 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

[260 281 248 276 272]


In [17]:
# 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = total_grade / 3
print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [18]:
# 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]
print(jeremy_test_2)

93


In [19]:
# Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]
print(manual_adwoa_test_1)

[94 88]


In [20]:
# 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]


In [24]:
# 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
tanya = student_scores[2,0]
print(tanya)

# 2차원 배열 슬라이싱: Cody의 전체 시험 점수
cody = student_scores[:,4]
print(cody)

89
[87 91 94]


In [25]:
"""
배열 원소 단위의 논리 연산
"""

# 논리연산 - 각 배열 원소 별로
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])
mask = a>5
print(mask)   # masking

[False  True False  True  True  True  True  True]


In [26]:
# 논리 연산을 이용하여 부분집합 구하기
selected = a[a>5]
print(selected)

[20  6 28 88  7 12]


In [27]:
# 논리식 결합: 논리합, 논리곱
selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

[ 1 20 28 88  7 12]
[6 7]


In [1]:
import numpy as np

In [31]:
# 정수 배열 생성
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,20,3))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19]


In [7]:
# 난수 배열 생성
np.random.seed(0)

arr = np.random.randint(10, size=(3,5))
print(arr)

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]


In [8]:
# 배열 속성
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)   # 4바이트 * 15개 = 60바이트

2
(3, 5)
15
int32
4
60


In [14]:
# 배열 슬라이싱
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [28]:
# 다차원 배열 슬라이싱
np.random.seed(0)
arr = np.random.randint(10, size=(6,8))
print(arr, '\n')

# 881 / 598 슬라이싱
print(arr[1:3, 4:7])

# 실습문제
print('\n', arr[:2, :3])
print('\n', arr[:3,::2])

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]] 

[[8 8 1]
 [5 9 8]]

 [[5 0 3]
 [2 4 7]]

 [[5 3 7 3]
 [2 7 8 1]
 [7 8 5 8]]


In [27]:
# 배열 슬라이스 = 뷰(view)
arr = arr[:4,:4]
print(arr)

arr_sub = arr[:2,:2]
print(arr_sub)

arr_sub[0,0] = 99
print(arr_sub)
print(arr)

[[5 0 3 3]
 [2 4 7 6]
 [7 7 8 1]
 [4 3 0 3]]
[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[99  0  3  3]
 [ 2  4  7  6]
 [ 7  7  8  1]
 [ 4  3  0  3]]


In [30]:
# .copy()
arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0,0] = 99
print(arr_sub)
print(arr)

[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]


In [3]:
# 배열 재구조화: reshape()
import numpy as np

x = np.arange(10)
print(x)

x_transformed = x.reshape(2,5)
print(x_transformed)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# 배열 재구조화: 차원 추가(np.newaxis)
arr = np.arange(3)
print(arr)
print(arr.shape, '\n')

arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape, '\n')

arr_new2 = arr[:, np.newaxis]
print(arr_new2)
print(arr_new2.shape, '\n')

arr_ones = np.ones((3,4))
print(arr_ones)
print(arr_ones.shape, '\n')

arr_ones_new = arr_ones[:, np.newaxis, :]
print(arr_ones_new)
print(arr_ones_new.shape)

[0 1 2]
(3,) 

[[0 1 2]]
(1, 3) 

[[0]
 [1]
 [2]]
(3, 1) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4) 

[[[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]

 [[1. 1. 1. 1.]]]
(3, 1, 4)


In [12]:
# 배열 연결: np.concatenate()
arr_1 = np.arange(1,4)
arr_2 = np.arange(4,7)
arr_3 = np.arange(7,10)
print(arr_1, arr_2, arr_3)

np.concatenate([arr_1, arr_2, arr_3])

[1 2 3] [4 5 6] [7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 배열 연결: 종연결(np.vstack()), 횡연결(np.hstack())
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [14]:
# 배열 분할: np.split()
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr, '\n')

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
