In [1]:
import numpy as np

In [2]:
# 역수 계산 함수 정의
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# 함수 테스트
x = np.arange(10)
compute_reciprocals(x)

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_7200/2325761507.py:5: RuntimeWarning: divide by zero encountered in true_divide
  output[i] = 1.0 / values[i]


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [3]:
"""
    역수 계산: Python loop vs NumPy ufuncs
"""

# 백만 개 크기의 난수 배열 생성
big_array = np.random.randint(1000, size=1000000)

# Python loop를 통한 역수 계산
%timeit compute_reciprocals(big_array)

C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_7200/2325761507.py:5: RuntimeWarning: divide by zero encountered in true_divide
  output[i] = 1.0 / values[i]


2.4 s ± 88.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
# NumPy ufunc을 통한 벡터화된 역수 계산
%timeit 1/big_array

<magic-timeit>:1: RuntimeWarning: divide by zero encountered in true_divide


4.09 ms ± 517 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
"""
    UFuncs: 유연한 연산 제공
"""

# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=(3,4))
arr2 = np.random.randint(10, size=(3,4))
print(arr1, '\n', arr2)

# 배열-스칼라 연산
arr1 = arr1 + 3
print('\n', arr1)

# 배열-배열 연산
arr3 = arr1 + arr2
print('\n', arr3)

arr4 = np.random.randint(10, size=(3, 5))
print('\n', arr4)

# 다차원 배열 연산: 1차원 배열 ** 2차원 배열
arr5 = arr4 ** 2   # 지수연산 같음..
print('\n', arr5)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 
 [[5 2 4 2]
 [4 7 7 9]
 [1 7 0 6]]

 [[ 8 11 12  8]
 [ 3  3  4 10]
 [ 9 12  5  7]]

 [[13 13 16 10]
 [ 7 10 11 19]
 [10 19  5 13]]

 [[9 9 7 6 9]
 [1 0 1 8 8]
 [3 9 8 7 3]]

 [[81 81 49 36 81]
 [ 1  0  1 64 64]
 [ 9 81 64 49  9]]


In [9]:
"""
    UFuncs: 산술 연산
"""

# Basic arithmetic operations on an array
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)
print()

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [10]:
"""
    UFuncs: 절댓값 계산
"""

# 절댓값 함수
x = np.array([-2,-1,0,1,2])
print(np.abs(x))

# 복소수에 대한 절댓값 계산
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [13]:
# np.linspace(): 선형 간격 벡터 생성
print(np.linspace(0,100,11))

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [14]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [2]:
# 집계 함수: reduce()
x = np.arange(1, 5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [3]:
# 집계 함수: accumulate()
accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[ 1  3  6 10]
[ 1  2  6 24]


In [4]:
# 집계 함수: sum()
np.random.seed(3)
arr = np.random.rand(1000000) # rand(): 0~1 사이의 실수 형태의 난수 배열 생성

In [5]:
# sum(): Python built-in function
%timeit sum(arr)

80 ms ± 859 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# np.sum()
%timeit np.sum(arr)

941 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
# 그 외의 집계함수
x = np.random.randint(0, 100, size=1000)

print("max =", np.max(x))
print("min =", np.min(x))
print("mean =", np.mean(x))
print("median =", np.median(x))
print("percentile =", np.percentile(x, 0.25))
print("variance =", np.var(x))
print("standard deviation =", np.std(x))
print("index of maximum value =", np.argmax(x))
print("index of minimum value =", np.argmin(x))
print()

# np.any()
print(np.any(x < 0))
print(np.any(x < 2))
print()

# np.all()
print(np.all(x > 0))   # 0이 있을 수 있어서 False
print(np.all(x >= 0))

max = 99
min = 0
mean = 48.777
median = 49.0
percentile = 0.0
variance = 817.091271
standard deviation = 28.584808395369734
index of maximum value = 65
index of minimum value = 86

False
True

False
True


In [19]:
# Multi dimensional aggregates
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
print(arr, '\n')

print(np.sum(arr))
print(np.sum(arr, axis = 0))   # 행 방향
print(np.sum(arr, axis = 1))   # 열 방향

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

54
[14 13 13 14]
[11 24 19]
